# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(515, 723)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_4.setContentsMargins(40, 5, 40, 5)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_5 = QtWidgets.QWidget(self.widget_6)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(150, -1, 150, -1)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.room = QtWidgets.QLabel(self.widget_5)
        self.room.setMinimumSize(QtCore.QSize(60, 30))
        self.room.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.room.setFont(font)
        self.room.setObjectName("room")
        self.horizontalLayout_4.addWidget(self.room)
        self.room_num = QtWidgets.QLineEdit(self.widget_5)
        self.room_num.setMinimumSize(QtCore.QSize(60, 35))
        self.room_num.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.room_num.setFont(font)
        self.room_num.setAlignment(QtCore.Qt.AlignCenter)
        self.room_num.setReadOnly(True)
        self.room_num.setObjectName("room_num")
        self.horizontalLayout_4.addWidget(self.room_num)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.widget_9 = QtWidgets.QWidget(self.widget_6)
        self.widget_9.setStyleSheet("")
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_2.setContentsMargins(100, 5, 100, -1)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tar = QtWidgets.QLabel(self.widget_9)
        self.tar.setMinimumSize(QtCore.QSize(200, 30))
        self.tar.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tar.setFont(font)
        self.tar.setAlignment(QtCore.Qt.AlignCenter)
        self.tar.setObjectName("tar")
        self.gridLayout_2.addWidget(self.tar, 0, 0, 1, 4, QtCore.Qt.AlignHCenter)
        self.tar_temp = QtWidgets.QLineEdit(self.widget_9)
        self.tar_temp.setMinimumSize(QtCore.QSize(80, 40))
        self.tar_temp.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tar_temp.setFont(font)
        self.tar_temp.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tar_temp.setReadOnly(True)
        self.tar_temp.setObjectName("tar_temp")
        self.gridLayout_2.addWidget(self.tar_temp, 1, 0, 1, 1)
        self.label1 = QtWidgets.QLabel(self.widget_9)
        self.label1.setMinimumSize(QtCore.QSize(20, 30))
        self.label1.setMaximumSize(QtCore.QSize(20, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 1, 1, 1, 1)
        self.tar_speed = QtWidgets.QLineEdit(self.widget_9)
        self.tar_speed.setMinimumSize(QtCore.QSize(100, 40))
        self.tar_speed.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tar_speed.setFont(font)
        self.tar_speed.setText("")
        self.tar_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.tar_speed.setReadOnly(True)
        self.tar_speed.setObjectName("tar_speed")
        self.gridLayout_2.addWidget(self.tar_speed, 1, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_9)
        self.mode = QtWidgets.QLineEdit(self.widget_6)
        self.mode.setMinimumSize(QtCore.QSize(100, 40))
        self.mode.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mode.setFont(font)
        self.mode.setAlignment(QtCore.Qt.AlignCenter)
        self.mode.setReadOnly(True)
        self.mode.setObjectName("mode")
        self.verticalLayout_4.addWidget(self.mode, 0, QtCore.Qt.AlignHCenter)
        self.widget_10 = QtWidgets.QWidget(self.widget_6)
        self.widget_10.setStyleSheet("")
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_3.setContentsMargins(100, -1, 100, -1)
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cur_speed = QtWidgets.QLineEdit(self.widget_10)
        self.cur_speed.setMinimumSize(QtCore.QSize(100, 40))
        self.cur_speed.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cur_speed.setFont(font)
        self.cur_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_speed.setReadOnly(True)
        self.cur_speed.setObjectName("cur_speed")
        self.gridLayout_3.addWidget(self.cur_speed, 2, 5, 1, 1)
        self.label2 = QtWidgets.QLabel(self.widget_10)
        self.label2.setMinimumSize(QtCore.QSize(20, 30))
        self.label2.setMaximumSize(QtCore.QSize(20, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.gridLayout_3.addWidget(self.label2, 2, 3, 1, 1)
        self.cur_temp = QtWidgets.QLineEdit(self.widget_10)
        self.cur_temp.setMinimumSize(QtCore.QSize(80, 40))
        self.cur_temp.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cur_temp.setFont(font)
        self.cur_temp.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.cur_temp.setReadOnly(True)
        self.cur_temp.setObjectName("cur_temp")
        self.gridLayout_3.addWidget(self.cur_temp, 2, 2, 1, 1)
        self.cur = QtWidgets.QLabel(self.widget_10)
        self.cur.setMinimumSize(QtCore.QSize(200, 30))
        self.cur.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cur.setFont(font)
        self.cur.setAlignment(QtCore.Qt.AlignCenter)
        self.cur.setObjectName("cur")
        self.gridLayout_3.addWidget(self.cur, 1, 2, 1, 4, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.widget_10)
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        self.widget_7.setMaximumSize(QtCore.QSize(16777206, 16777215))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_5.setContentsMargins(150, -1, 150, -1)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label3 = QtWidgets.QLabel(self.widget_7)
        self.label3.setMinimumSize(QtCore.QSize(45, 30))
        self.label3.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.horizontalLayout_5.addWidget(self.label3)
        self.cost = QtWidgets.QLineEdit(self.widget_7)
        self.cost.setMinimumSize(QtCore.QSize(80, 40))
        self.cost.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cost.setFont(font)
        self.cost.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.cost.setReadOnly(True)
        self.cost.setObjectName("cost")
        self.horizontalLayout_5.addWidget(self.cost)
        self.verticalLayout_4.addWidget(self.widget_7)
        self.horizontalLayout_3.addWidget(self.widget_6)
        self.horizontalLayout.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setMinimumSize(QtCore.QSize(200, 300))
        self.widget_4.setMaximumSize(QtCore.QSize(200, 300))
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.Button_sub = QtWidgets.QPushButton(self.widget_4)
        self.Button_sub.setMinimumSize(QtCore.QSize(80, 45))
        self.Button_sub.setMaximumSize(QtCore.QSize(80, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Button_sub.setFont(font)
        self.Button_sub.setObjectName("Button_sub")
        self.gridLayout.addWidget(self.Button_sub, 1, 0, 1, 1)
        self.Button_mode = QtWidgets.QPushButton(self.widget_4)
        self.Button_mode.setMinimumSize(QtCore.QSize(80, 45))
        self.Button_mode.setMaximumSize(QtCore.QSize(80, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_mode.setFont(font)
        self.Button_mode.setObjectName("Button_mode")
        self.gridLayout.addWidget(self.Button_mode, 0, 1, 1, 1)
        self.Button_speed = QtWidgets.QPushButton(self.widget_4)
        self.Button_speed.setMinimumSize(QtCore.QSize(150, 45))
        self.Button_speed.setMaximumSize(QtCore.QSize(150, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_speed.setFont(font)
        self.Button_speed.setObjectName("Button_speed")
        self.gridLayout.addWidget(self.Button_speed, 2, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.Button_out = QtWidgets.QPushButton(self.widget_4)
        self.Button_out.setMinimumSize(QtCore.QSize(150, 45))
        self.Button_out.setMaximumSize(QtCore.QSize(150, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_out.setFont(font)
        self.Button_out.setObjectName("Button_out")
        self.gridLayout.addWidget(self.Button_out, 3, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.Button_plus = QtWidgets.QPushButton(self.widget_4)
        self.Button_plus.setMinimumSize(QtCore.QSize(80, 45))
        self.Button_plus.setMaximumSize(QtCore.QSize(80, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Button_plus.setFont(font)
        self.Button_plus.setObjectName("Button_plus")
        self.gridLayout.addWidget(self.Button_plus, 1, 1, 1, 1)
        self.Button_open = QtWidgets.QPushButton(self.widget_4)
        self.Button_open.setMinimumSize(QtCore.QSize(80, 45))
        self.Button_open.setMaximumSize(QtCore.QSize(80, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_open.setFont(font)
        self.Button_open.setObjectName("Button_open")
        self.gridLayout.addWidget(self.Button_open, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 6)
        self.verticalLayout.setStretch(1, 5)

        self.retranslateUi(Form)
        self.Button_open.clicked.connect(Form.switch_click)
        self.Button_mode.clicked.connect(Form.button_mode_click)
        self.Button_speed.clicked.connect(Form.button_speed_click)
        self.Button_plus.clicked.connect(Form.button_plus_click)
        self.Button_sub.clicked.connect(Form.button_sub_click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.room.setText(_translate("Form", "房间号"))
        self.room_num.setText(_translate("Form", "01"))
        self.tar.setText(_translate("Form", "设  定"))
        self.label1.setText(_translate("Form", "℃"))
        self.label2.setText(_translate("Form", "℃"))
        self.cur.setText(_translate("Form", "实  时"))
        self.label3.setText(_translate("Form", "金额"))
        self.Button_sub.setText(_translate("Form", "-"))
        self.Button_mode.setText(_translate("Form", "模式"))
        self.Button_speed.setText(_translate("Form", "风速"))
        self.Button_out.setText(_translate("Form", "退房"))
        self.Button_plus.setText(_translate("Form", "+"))
        self.Button_open.setText(_translate("Form", "开/关"))
